### PR TITLE
Fixed bugs related to react 16

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:
- Open **translationWords** and you should not get the following errors in your console.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/84)

### CODE REVIEW

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84#-:-L3oAdh_-3KoC3wsC5pp:bnfp4nl)*

**Comment by richmahn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/components/Verse.js, line 134 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84#-L3oHrY36sw2J8_6GvEe:-L3oHrY36sw2J8_6GvEf:bbpr8di) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/8778be5efd486c8f3c897f319afcaa7964621c32/src/components/Verse.js#L134)):*
> ```JavaScript
> Verse.propTypes = {
>   actions: PropTypes.object.isRequired,
>   verseText: PropTypes.string.isRequired,
> ```

This being string makes me get this error:

C:\web\translationCore\node_modules\fbjs\lib\warning.js:33 Warning: Failed prop type: Invalid prop `verseText` of type `array` supplied to `Verse`, expected `string`.

Changing it to 'any' has it not give this error. Given that there is a check (above in your changes) that looks to see if it is a string otherwise runs this.verseArray(), shouldn't this remain 'any'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84)*

**Comment by richmahn** [comment]
Retracting the above LGTM.... see inline comments.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84#-:-L3oILB6uR78czFiNRM_:bmiiu1s)*

**Comment by mannycolon** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/Verse.js, line 134 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84#-L3oHrY36sw2J8_6GvEe:-L3oiLDqKG-QHbp-7eD8:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/8778be5efd486c8f3c897f319afcaa7964621c32/src/components/Verse.js#L134)):*
<details><summary><i>Previously, richmahn (Richard Mahn) wrote…</i></summary><blockquote>

This being string makes me get this error:

C:\web\translationCore\node_modules\fbjs\lib\warning.js:33 Warning: Failed prop type: Invalid prop `verseText` of type `array` supplied to `Verse`, expected `string`.

Changing it to 'any' has it not give this error. Given that there is a check (above in your changes) that looks to see if it is a string otherwise runs this.verseArray(), shouldn't this remain 'any'?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84)*

**Comment by richmahn** [comment]
:LGTM:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/84#-:-L3omovTnIXplYx3Tyh1:bmxilld)*

**Pull request merged**
