### PR TITLE
scripture pane module refactor

### PR DESCRIPTION
**Pull request by mannycolon**
---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/5)

### CODE REVIEW

**Comment by ihoegen** [comment]
I won't merge until the separation is made.

**Comment by mannycolon** [comment]
@ihoegen that's fine I'm still working on it

**Comment by mannycolon** [comment]
@ihoegen I'm done separating presentational and container component

**Comment by ihoegen** [comment]
Reviewed 1 of 3 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Container.js, line 151 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/5#-K_g85idfNkk0nYc74YM:-K_g85idfNkk0nYc74YN:b8ycusa) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/2dc15126809985ca8ea62251fa9df14d60e3b40a/Container.js#L151)):*
> ```JavaScript
>         currentPaneSettings={this.state.currentPaneSettings}
>         currentCheck={this.state.currentCheck}
>         originalLanguage={this.state.originalLanguage}
> ```

Could you use {...this.state} to simplify this?

---

*[Pane.js, line 6 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/5#-K_g8FdnakpnW4OewaT5:-K_g8FdoaOwgui858XU2:b-ay7geo) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/2dc15126809985ca8ea62251fa9df14d60e3b40a/Pane.js#L6)):*
> ```JavaScript
> const RB = api.ReactBootstrap;
> const {Col, Well, Glyphicon} = RB;
> const style = require('./Style');
> ```

Maybe we could pass style down from the container

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/5)*

**Comment by ihoegen** [comment]
`C:\Users\Ian\AppData\Roaming\translationCore\packages-compiled\ScripturePane\FetchData.js:182 Error: Cannot find module './Lexicon.json'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (C:\Users\Ian\Documents\Work\tC\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at parseGreek (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/ScripturePane/FetchData.js:266:13)
    at readInOriginal (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/ScripturePane/FetchData.js:185:9)
    at C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/ScripturePane/FetchData.js:80:9
    at Dispatcher.run (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/ScripturePane/FetchData.js:114:7)
    at fetchData (C:/Users/Ian/AppData/Roaming/translationCore/packages-compiled/ScripturePane/FetchData.js:84:14)
`

**Comment by mannycolon** [comment]
@ihoegen style is not something that belongs to the container but the presentational component 
(in this case View.js)

**Comment by ihoegen** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/5)*

**Comment by ihoegen** [comment]
@mannycolon I got it working, is it ready for a merge on your end?

**Pull request merged**
