### PR TITLE
made changes to accommodate new scripturepane settings implemenation

### PR DESCRIPTION
**Pull request by mannycolon**
#### This pull request addresses:

- Please follow instructions on
https://github.com/unfoldingWord-dev/translationCore/pull/1943

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/55)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55)*

**Comment by klappy** [comment]
*[components/chapterView/BibleHeadingsRow.js, line 15 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55#-KnGoTBUCG5ufAYltnXB:-KnGoTBUCG5ufAYltnXC:b6bylre) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/f3d1f6901411be9f3611d1365cd70b0343f02c11/components/chapterView/BibleHeadingsRow.js#L15)):*
> ```JavaScript
>       bibleHeadings = currentPaneSettings.map((bibleId, index) => {
>         let { language_name, resource_title, resource_id, direction } = bibles[bibleId]["manifest"];
>         let resourceText = bibleId !== "targetLanguage" ? " (" + resource_title.toUpperCase() + ")" : "" ;
> ```

This results in it showing as "Greek (UNLOCKED GREEK NEW TESTAMENT)" and "English (UNLOCKED LITERAL BIBLE)", we want those to show as "Greek (UGNT)" and "English (ULB)"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55)*

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/chapterView/BibleHeadingsRow.js, line 15 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55#-KnGoTBUCG5ufAYltnXB:-KnI6tTFZyKKMyT4KRNM:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/f3d1f6901411be9f3611d1365cd70b0343f02c11/components/chapterView/BibleHeadingsRow.js#L15)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This results in it showing as "Greek (UNLOCKED GREEK NEW TESTAMENT)" and "English (UNLOCKED LITERAL BIBLE)", we want those to show as "Greek (UGNT)" and "English (ULB)"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/55#-:-KnJwP0_9w2X_B32gpTv:bnfp4nl)*

**Pull request merged**
