### PR TITLE
Feature - #2843 - Makes it obvious when Greek text not available

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Address issue https://github.com/unfoldingWord-dev/translationCore/issues/2843. It actually addresses any verse missing from any Bible translation. 

**NOTE:** This also moves the PLACE HOLDER (i.e. warning text) constant into the Verse component rather than components that render Verse to set the text, but rather just pass `null` and Verse.js checks if it is null and displays the warning. This is because 1) two places were setting the place holder and 2) Verse needs to know it is a place holder so it can style it correctly.

#### How to test this pull request:

1) Load a project of a book other than Titus. Go into tW tool and you should see for any verse the Greek column says "[WARNING: This Bible version does not include text for this reference.]"

2) Remove/rename the the `~/translationCore/resources/en/bibles/ulb/v11/tit` directory from your home directory. Reload the tC app, load a Titus project, go into tW tool for that project, load the resource in the Scripture Pane if not already, and it also should give you the warning.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/73)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/73)*

**Comment by PhotoNomad0** [comment]
Was able to reproduce the warning.

:lgtm:

**Comment by RoyalSix** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/73)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/73#-:-Kz0QL5oXiZcLylYw4_X:bnfp4nl)*

**Comment by RoyalSix** [comment]
@richmahn All good except for merge conflicts

**Comment by richmahn** [comment]
@RoyalSix Yup, merge conflicts were expected since all these PRs had to set up testing environments.

**Pull request merged**
