### PR TITLE
Target Language Word Highlighting in the Scripture Pane 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Target Language Word Highlighting in the Scripture Pane
- **Dependency:** https://github.com/unfoldingWord-dev/translationCore/pull/3905

#### Please include detailed Test instructions for your pull request:
- Open a Titus project with **tW** and make a selection in the verse check area and as you save your selection/s it should Highlighting in the target language pane in the Scripture Pane.
- Make sure to add the target language pane to the scripture Pane if you didn't previously add it.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/95)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/95)*

**Comment by RoyalSix** [comment]
Code Review: ```LGTM```

**Comment by klappy** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/95)*

**Comment by PhotoNomad0** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/95)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/95#-:-L6IVek-fxATabFXJD1J:bnfp4nl)*

**Pull request merged**
