### PR TITLE
Feature #3273 /Add New verse object support for UGNT resources

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Add New verse object support for UGNT resources

#### How to test this pull request:

Test using: https://github.com/unfoldingWord-dev/translationCore/pull/3639

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/82)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/components/Verse.js, line 44 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82#-L2fwSUTSTq_LbIhtsIo:-L2fwSUTSTq_LbIhtsIp:b-10ypvh) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/2b58e96c1b9893cac0987a8bd767eaec23a911d4/src/components/Verse.js#L44)):*
> ```JavaScript
>         return (
>           <span style={{cursor: 'pointer'}} onClick={(e)=>this.onClick(e, word)} key={index}>
>             {(word.word || word.text) + " "}
> ```

I'm wondering how we will handle punctuation when it gets here.
For example, the last word in a sentence would have a space added and the period would come after this having a space before it where it shouldn't.
I'm wondering if we should have an attribute for certain types of verseObjects that conditionally prevent a space before or after the verseObject.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82)*

**Comment by klappy** [comment]
*[src/components/Verse.js, line 44 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82#-L2fwSUTSTq_LbIhtsIo:-L2fwxpWXzIlmJ1-p8Be:b62iadw) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/2b58e96c1b9893cac0987a8bd767eaec23a911d4/src/components/Verse.js#L44)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm wondering how we will handle punctuation when it gets here.
For example, the last word in a sentence would have a space added and the period would come after this having a space before it where it shouldn't.
I'm wondering if we should have an attribute for certain types of verseObjects that conditionally prevent a space before or after the verseObject.
</blockquote></details>

We may be able to punt and handle this at a later point, but feel that it will be needed soon.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82)*

**Comment by klappy** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82#-:-L2fx6mBiSo-gc0d67SR:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82)*

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/Verse.js, line 44 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82#-L2fwSUTSTq_LbIhtsIo:-L3-JZ7rYAMtNAcS7PVx:b-6xdq3h) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/2b58e96c1b9893cac0987a8bd767eaec23a911d4/src/components/Verse.js#L44)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

We may be able to punt and handle this at a later point, but feel that it will be needed soon.
</blockquote></details>

Good point, but currently it looks like the space is here to keep the words from running together.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/82)*

**Pull request merged**
