### PR TITLE
Bugfix - #3198 - Close button and Console Error when missing verse in tW

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Bugfix for issue https://github.com/unfoldingWord-dev/translationCore/issues/3198

#### How to test this pull request:

Follow instructions in the issue to download/unzip a project and open tW (https://github.com/unfoldingWord-dev/translationCore/issues/3198)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/76)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/76#-:-L0PGMhvlILBtfhx0IoG:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Works for me - just need one more review.

**Comment by RoyalSix** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/components/Verse.js, line 14 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/76#-L0PiYfnTi3Mo24Tvy9X:-L0PiYfnTi3Mo24Tvy9Y:b4ogqzd) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/919c5198c36ced48e6c3763e9ca3e61ed5050d59/src/components/Verse.js#L14)):*
> ```JavaScript
> 
>   componentWillReceiveProps(nextProps) {
>     if (this.props.verseText !== nextProps.verseText && nextProps.verseText !== null) {
> ```

I know you didn't start the triple nested if statement with no else but it might look cleaner to just have one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/76)*

**Comment by RoyalSix** [comment]
Not sure what is going on but I am getting this error after doing the above steps.
It happens on the press Save & Continue step and the app gets locked up.
screen shot 2017-12-15 at 7 20 30 am

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/76#-:-L0f3uomPuBiQsDeAiIg:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Don't see the error jay saw.

**Pull request merged**
