### PR TITLE
Punctuation in the middle of a word now highlights in the Scripture Pane

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Punctuation in the middle of a word now highlights in the Scripture Pane

#### Please include detailed Test instructions for your pull request:
- Open the following checks and verify that the punctuation is highlighted
   - [ ] God Titus 2:5, Titus 1:7

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [x] Checkout the branch locally and ensure that app runs as expected
  - [x] Ensure tests pass
  - [x] Open and watch the console for errors
  - [x] Make sure all actions perform as expected
  - [x] Import and Load a new Project
  - [x] Load a tool and perform basic actions
  - [x] Switch tools and perform basic actions
  - [x] Switch project to an existing project
  - [x] Load a tool and perform basic actions
  - [x] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [x] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/111)

### CODE REVIEW

**Comment by bspidel** [comment]
Functionality  :lgtm:
Code :lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/111#-:-L8iRDBp1AcerfyvdkyI:b-qw5nod)*

**Comment by RoyalSix** [comment]
Local Testing: `LGTM`
 - No way to test `self-control` because its not in Titus
Code Review: `Pending...`

**Comment by RoyalSix** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/helpers/highlightHelpers.js, line 151 at r2](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/111#-L8i_vON-Daqqswnc2He:-L8i_vON-Daqqswnc2Hf:bwo1hn1) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1ebf741a26143a082482d3a0961559d2c6b9dc0e/src/helpers/highlightHelpers.js#L151)):*
> ```JavaScript
>   // handle nested next words
>   if (nextWord) {
>     if (Array.isArray(nextWord) || Array.isArray(nextWord[0])) {
> ```

Should this be a `&&` rather than `||`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/111)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/helpers/highlightHelpers.js, line 151 at r2](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/111#-L8i_vON-Daqqswnc2He:-L8idCaC26KhhExRf9a9:b32w12) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1ebf741a26143a082482d3a0961559d2c6b9dc0e/src/helpers/highlightHelpers.js#L151)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Should this be a `&&` rather than `||`
</blockquote></details>

No

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/111)*

**Pull request merged**
