### PR TITLE
Added Highlighted words to Greek and ULB Pane 

### PR DESCRIPTION
**Pull request by mannycolon**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Added Highlighted words to Greek and GL Pane 

#### Please include detailed Test instructions for your pull request:
- [ ] Open a brand new/fresh project with tW
- [ ] Words should highlight in both greek (ugnt) and English (ulb)
- [ ] Open an old project with tW and it should not show Highlighted words in the scripture pane but open with no problems.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/93)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
Unit tests aren't passing.

**Comment by PhotoNomad0** [comment]
ULB words are now clickable (hand pointer) even when there is no strong number.

**Comment by PhotoNomad0** [comment]
I tried selecting a word for life on tit 1:2, but the ULB does not highlight.  (this is on a new USFM import of titus)

**Comment by PhotoNomad0** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/Verse.js, line 56 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5n_Q9sNbWb6RHjqEwU:-L5n_Q9sNbWb6RHjqEwV:bnnr17t) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1f1acffd42f7a6bdd011fc903feebaaf537f3c75/src/components/Verse.js#L56)):*
> ```JavaScript
>           isHighlightedWord = text === contextId.quote;
>         } else if (bibleId === 'ulb') {
>           isHighlightedWord = word.content === contextId.quote;
> ```

this also should also check word.text for new verseObjects.

---

*[src/components/Verse.js, line 73 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5n_mBelcBp4F_G9gDR:-L5n_mBelcBp4F_G9gDS:b-tdemmm) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1f1acffd42f7a6bdd011fc903feebaaf537f3c75/src/components/Verse.js#L73)):*
> ```JavaScript
>             <span
>               key={index}
>               style={{ cursor: 'pointer', backgroundColor: isHighlightedWord ? "var(--highlight-color)" : "" }}
> ```

don't think we want to use the pointer cursor if there is no strongs number to show.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by mannycolon** [comment]
> I tried selecting a word for life on tit 1:2, but the ULB does not highlight. (this is on a new USFM import of titus)

What do you mean?
Making selection in the verse check isn't related to the **ulb** highlighting

**Comment by mannycolon** [comment]
> the ULB does not highlight.

Sorry, I forgot to also make a PR for changes I made in the core.

**Comment by klappy** [comment]
This is looking really good. Quick question... is it possible to exclude the space preceding the word(s) in the highlight? It seems odd that the spaces are highlited and not skipping the space and only highlighting the characters. You can highlight the whitespace between words, just not the whitespace before it.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5otjetmHwEUDqvp-Ke:bz1s9bb)*

**Comment by klappy** [comment]
Also, for the checks for `Jesus Christ`, I'm not seeing any highlights. 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5ouZy8E1N3b7n9FrWa:b-hvfcsb)*

**Comment by klappy** [comment]
I should specify that it is in all the checks for `Jesus Christ` for Titus, that there is no highlighting for Greek or ULB.


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5oufeK9Rtv2dXecC4-:b82k8pi)*

**Comment by PhotoNomad0** [comment]
Reviewed 6 of 7 files at r2.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/Verse.js, line 56 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5n_Q9sNbWb6RHjqEwU:-L5ozMr1Rdu7hklpT5v2:bhzxvso) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1f1acffd42f7a6bdd011fc903feebaaf537f3c75/src/components/Verse.js#L56)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

this also should also check word.text for new verseObjects.
</blockquote></details>

OK, understand where content is coming from now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
I am seeing the same thing as Klappy.  Set a breakpoint in verse component and discovering that contextId.quote
is trying to match "Ἰησοῦ Χριστοῦ".  It looks like since words Jesus and Christ are both in a milestone "Ἰησοῦ" and Christ is also in milestone "Χριστοῦ".  It's going to require more complicated matching.  I think we should check if word.content matches any of the words in contextId.quote.  Also we probably will have to make word.content an array and check if any of the words in the array match any of the words in contextId.quote.

---

Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5p-YoI7JqWEbnhEK-7:b4o7n7u)*

**Comment by PhotoNomad0** [comment]
The previous was for UGNT highlighting.

---

Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5p3hR9mztHqc4Z1TFc:bw9t4t7)*

**Comment by mannycolon** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/Verse.js, line 56 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5n_Q9sNbWb6RHjqEwU:-L5r-nKysMsXZ2btqx-c:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1f1acffd42f7a6bdd011fc903feebaaf537f3c75/src/components/Verse.js#L56)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

OK, understand where content is coming from now.
</blockquote></details>

Done.

---

*[src/components/Verse.js, line 73 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5n_mBelcBp4F_G9gDR:-L5r-ohnJy-a2_sBMZG_:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1f1acffd42f7a6bdd011fc903feebaaf537f3c75/src/components/Verse.js#L73)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

don't think we want to use the pointer cursor if there is no strongs number to show.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by mannycolon** [comment]
> is it possible to exclude the space preceding the word(s) in the highlight?
@klappy 

Done

**Comment by mannycolon** [comment]
> I am seeing the same thing as Klappy. Set a breakpoint in verse component and discovering that contextId.quote
> is trying to match "Ἰησοῦ Χριστοῦ". It looks like since words Jesus and Christ are both in a milestone "Ἰησοῦ" and Christ is also in milestone "Χριστοῦ". It's going to require more complicated matching. I think we should check if word.content matches any of the words in contextId.quote. Also we probably will have to make word.content an array and check if any of the words in the array match any of the words in contextId.quote.
@PhotoNomad0 

Done

**Comment by mannycolon** [comment]
#### This is a list of checks that are currently missing the highlighting for Greek and/or ULB.

- Testimony, testify 
     - 1:13 
- God
     - Titus 2:5, Titus 2:11
- godly, godliness
     - Titus 2:12
- good, goodness 
     - Titus 3:8 (both ugnt and ulb) 
- grace, gracious 
     - Titus 3:15 
- holy, holiness
     - Titus 3:5 (ugnt)
- Savior, savior 
     - Titus 2:10, Titus 3:6
- world, worldly
     - Titus 2:12
- exhort, exhortation 
     - Titus 2:15

**Comment by PhotoNomad0** [comment]
Seeing a crash when I try to open WA:

Uncaught TypeError: Cannot read property 'split' of undefined
    at /Users/blm/Development/Electron/testDir/translationCore/tC_apps/ScripturePane/src/components/Verse.js:57:31
    at Array.map (native)
    at Verse.verseArray (/Users/blm/Development/Electron/testDir/translationCore/tC_apps/ScripturePane/src/components/Verse.js:48:29)
    at Verse.render (/Users/blm/Development/Electron/testDir/translationCore/tC_apps/ScripturePane/src/components/Verse.js:126:24)
    at finishClassComponent (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:7873:31)
    at updateClassComponent (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:7850:12)
    at beginWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:8225:16)
    at performUnitOfWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:10224:16)
    at workLoop (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:10288:26)
    at HTMLUnknownElement.callCallback (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:542:14)
    at Object.invokeGuardedCallbackDev (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:581:16)
    at invokeGuardedCallback (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:438:27)
    at renderRoot (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:10366:7)
    at performWorkOnRoot (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:11014:24)
    at performWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:10967:7)
    at requestWork (/Users/blm/Development/Electron/testDir/translationCore/node_modules/react-dom/cjs/react-dom.development.js:10878:7)

Looks like the problem is here:

          isHighlightedWord = contextId.quote.split(' ').includes(word.text);

when  contextId.quote is undefined

**Comment by PhotoNomad0** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/Verse.js, line 61 at r3](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5tkj000DMr6XfeJW4k:-L5tkj000DMr6XfeJW4l:b-1b2ee5) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/bafc0c06b2d35f43d022ea78eb912aa2b6730fd5/src/components/Verse.js#L61)):*
> ```JavaScript
>             contextId.quote.split(' ').includes(previousWord.text) && isHighlightedWord : false;
>         } else if (bibleId === 'ulb') {
>           isHighlightedWord = contextId.quote.split(' ').includes(word.content);
> ```

Need to make sure  contextId.quote is defined before trying to split.  Otherwise will crash in WA tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
Review status: 12 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/components/Verse.js, line 57 at r3](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5tl34LxgGhWlsgPE-T:-L5tl34LxgGhWlsgPE-U:b-1b2ee5) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/bafc0c06b2d35f43d022ea78eb912aa2b6730fd5/src/components/Verse.js#L57)):*
> ```JavaScript
> 
>         if (bibleId === 'ugnt') {
>           isHighlightedWord = contextId.quote.split(' ').includes(word.text);
> ```

Need to make sure  contextId.quote is defined before trying to split.  Otherwise will crash in WA tool.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
A little weirdness here: 

screen shot 2018-02-21 at 2 49 46 pm

screen shot 2018-02-21 at 2 50 11 pm

**Comment by klappy** [comment]
I'm wondering if that had to do with data issues where the user couldn't tell which occurrence of the word they were highlighting.

**Comment by PhotoNomad0** [comment]
> I'm wondering if that had to do with data issues where the user doing the aligning couldn't tell which occurrence of the word they were highlighting.

@klappy - Looks like you are right.  Once the verse.js gets fixed, I guess we are good to go.

**Comment by mannycolon** [comment]
@PhotoNomad0 @klappy That problem in the screenshot is a data/alignment problem. the user aligned the wrong ULB words to the Greek.

**Comment by PhotoNomad0** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5uQ_w6hfeDTo0afGZJ:bnfp4nl)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/Verse.js, line 57 at r3](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5tl34LxgGhWlsgPE-T:-L5uT0ZGoECMT4xMriMP:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/bafc0c06b2d35f43d022ea78eb912aa2b6730fd5/src/components/Verse.js#L57)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to make sure  contextId.quote is defined before trying to split.  Otherwise will crash in WA tool.
</blockquote></details>

Done.

---

*[src/components/Verse.js, line 61 at r3](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-L5tkj000DMr6XfeJW4k:-L5uT1KSzfsc9S04utbo:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/bafc0c06b2d35f43d022ea78eb912aa2b6730fd5/src/components/Verse.js#L61)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

Need to make sure  contextId.quote is defined before trying to split.  Otherwise will crash in WA tool.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L5x6PT4bWSjlHE20Dwh:bnfp4nl)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r1, 6 of 7 files at r2, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/93#-:-L63q3IWhm-b1ZYRsVlm:bnfp4nl)*

**Pull request merged**
