### PR TITLE
Added UDB to

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:

Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.
relevant information in https://github.com/unfoldingWord-dev/translationCore/pull/797

#### How to test this pull request:

Include testing instructions so that other developers know what to look for, and how to make sure that your feature/bugfix/enhancement really works.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/19)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[components/AddPaneModal.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19#-Ke4cp0fS7IwXJBBNMk4:-Ke4cp0fS7IwXJBBNMk5:b-319coq) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/f2a4435531b5a84c94525aa36a7d4aca3384d03a/components/AddPaneModal.js#L10)):*
> ```JavaScript
> const RB = api.ReactBootstrap;
> const {Modal, Button, FormControl} = RB;
> const {dialog} = remote;
> ```

where do you use dialog???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19)*

**Comment by mannycolon** [comment]
@RoyalSix Im getting the following error:
```
Uncaught TypeError: Cannot read property 'heading' of undefined /Users/mannycolon/tcprojects/translationCore/tC_apps/ScripturePane/components/Pane.js:66
```

**Comment by mannycolon** [comment]
@RoyalSix it seems that scripture pane used to get the original language for the tool to use 
 this error comes from the scriptur pane fetchData	@	FetchData.js [sm]:97
``` 
Can't find original language requirements.js:20
```

**Comment by mannycolon** [comment]
@RoyalSix I pull your PR in develop.

now I'm only missing the ULB and the UDB highlighted word is buggy on importantWords.

**Comment by RoyalSix** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[components/AddPaneModal.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19#-Ke4cp0fS7IwXJBBNMk4:-Ke4qgFgh-ouTUdGwqEu:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/f2a4435531b5a84c94525aa36a7d4aca3384d03a/components/AddPaneModal.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

where do you use dialog???
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[FetchData.js, line 98 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19#-Ke52uWjuY8eLF1sL8UD:-Ke52uWjuY8eLF1sL8UE:bmseil0) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/412c21d9f8f1432993eab2f85c122bf30383564b/FetchData.js#L98)):*
> ```JavaScript
>     if (!params.gatewayLanguageUDBPath) {
>       params.gatewayLanguageUDBPath = path.join(window.__base, 'static', 'taggedUDB');
>       console.warn("This project is using old params data")
> ```

i like the warning msg. good job!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/19)*

**Pull request merged**
