### PR TITLE
Bugfix #3299/Cleanup defunct code & fix linting errors

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### This pull request addresses:

Cleanup defunct code & fix linting errors

#### How to test this pull request:

test any of the tools.  Should not see any NEW scripture pane errors.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/81)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81)*

**Comment by klappy** [comment]
Looking good. I'm still getting linting errors for components not having props defined in PropTypes.
Do you mind adding that to the components?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2Mku4DNdktHRw-CVOw:b-fo0deq)*

**Comment by PhotoNomad0** [comment]
Where do you see these errors?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2MxeS4gcaEj7Hi2aFD:btme3qq)*

**Comment by PhotoNomad0** [comment]
I see that propTypes were never defined for these components, but not seeing a lint error.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2MyE_xNVQ1bcHmEPl9:bixetn1)*

**Comment by klappy** [comment]
Where the variables are defined and pulled from the props. 
My editor shows alerts maybe not errors.

**Comment by PhotoNomad0** [comment]
Thanks - since I am using InteliJ, discovered that I needed to manually enable eslint for the project to get it to read the .eslintrc file and enable react linting.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2PsUrw6tqMQsr50nLS:b-4f9wex)*

**Comment by PhotoNomad0** [comment]
Have made a bunch of cleanups and scripture pane still renders.  Ready for another review.

---

Review status: 2 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2R9qHd_ysZK77I9A4e:b-lil3n5)*

**Comment by PhotoNomad0** [comment]
Review status: 2 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/chapterView/ChapterView.js, line 17 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-L2RAsRzDo8XgJjZo8Cu:-L2RAsRzDo8XgJjZo8Cv:b-lq1xx) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1893a5914817bef057b9233a1b56ff79536ecd25/src/components/chapterView/ChapterView.js#L17)):*
> ```JavaScript
> /* eslint-disable react/no-find-dom-node */
>     let element = ReactDOM.findDOMNode(currentVerse);
> /* eslint-enable react/no-find-dom-node */
> ```

@klappy - Had a couple warnings that we shouldn't be accessing the dom node this way.  How should this be done?  Hoping it is easy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81)*

**Comment by klappy** [comment]
*[src/components/chapterView/ChapterView.js, line 17 at r2](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-L2RAsRzDo8XgJjZo8Cu:-L2RSphrhNqQNAQrNxNa:bcuowes) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/1893a5914817bef057b9233a1b56ff79536ecd25/src/components/chapterView/ChapterView.js#L17)):*
<details><summary><i>Previously, PhotoNomad0 (Bruce McLean) wrote…</i></summary><blockquote>

@klappy - Had a couple warnings that we shouldn't be accessing the dom node this way.  How should this be done?  Hoping it is easy.
</blockquote></details>

That's a good question. I've not run into this or sure there is another way that is easy. Is this a lifecycle problem, doing this on the mounting of the component? Or is it something that React doesn't like at all?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81)*

**Comment by klappy** [comment]
Reviewed 16 of 16 files at r2.
Review status: 15 of 18 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81)*

**Comment by klappy** [comment]
:lgtm: 
Not sure what to do about the React warning about finding the dom element in the componentDidMount.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2RTq96-g0QTUAjd02v:beg9q3a)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81)*

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 13 of 16 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/81#-:-L2W6ABiI_65AV2-z0Dt:bnfp4nl)*

**Pull request merged**
