### PR TITLE
Refactor Fetch Data

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR allows us to run fetch datas and send progress to the core app.

#### How to test this pull request:
Try and load a tool. Right now the UI is getting blocked so you cannot check the progress but if you console app js you can confirm it is working.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/29)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[FetchData.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf0wijasl81odfYS3J:-Kgf0wijasl81odfYS3K:b8485m4) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L10)):*
> ```JavaScript
> const NAMESPACE = "ScripturePane";
> const defaultSave = path.join(pathex.homedir(), 'translationCore');
> const api = window.ModuleApi;
> ```

can we remove the API??

---

*[FetchData.js, line 17 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf16goSvBEw5LWnUKA:-Kgf16gp-8ZReZQ17f4g:b-lb6m4p) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L17)):*
> ```JavaScript
>   return new Promise(function (resolve, reject) {
>     /**
>       * @description Fetch data.
> ```

the jsdoc documentation should go before the function ?? lol

---

*[FetchData.js, line 118 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf1X5Mic5yqJKwysk8:-Kgf1X5Mic5yqJKwysk9:bzh7z2q) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L118)):*
> ```JavaScript
>     * check if original language is already in common
>     * get it if it isn't using parsers and params
>     ******************************************************************************/
> ```

this maybe too picky but can we do 
/**
     * Get the x value.
     * @return {number} The x value.
     */

instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29)*

**Comment by mannycolon** [comment]
@RoyalSix like I said in the other PR lets move this file to the tools repo. in this case the translationWords repo.

**Comment by RoyalSix** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[FetchData.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf0wijasl81odfYS3J:-KgkmogojMjM1f7Jh6oJ:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we remove the API??
</blockquote></details>

Done.

---

*[FetchData.js, line 17 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf16goSvBEw5LWnUKA:-Kgkmpeh5ksuwy-J-Zmb:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L17)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

the jsdoc documentation should go before the function ?? lol
</blockquote></details>

Done.

---

*[FetchData.js, line 118 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-Kgf1X5Mic5yqJKwysk8:-KgkmxM5Q45EabetOrg1:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/fea48d9856726748938b76a2ded967914d4b8a48/FetchData.js#L118)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this maybe too picky but can we do 
/**
     * Get the x value.
     * @return {number} The x value.
     */

instead
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29)*

**Comment by RoyalSix** [comment]
Done.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29#-:-KgkrZ6qp6_j68lvMxXI:b-896fix)*

**Comment by mannycolon** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/29)*

**Pull request merged**
