### PR TITLE
Sandbox feature usfm3

### PR DESCRIPTION
**Pull request by klappy**
#### This pull request addresses:

Lots of USFM changes from importing to exporting to alignment data, and usage in tools.

#### How to test this pull request:

Requires checking out branches from `translationCore`, `ScripturePane` and `WordAlignmentTool`.
Test the entire app make sure all works as intended.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/88)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
Could merge in https://github.com/translationCoreApps/ScripturePane/pull/89 before or after merging to develop.

---

Reviewed 5 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/88#-:-L5-a8ZLrbtp486qBG26:b2gdq9w)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/88#-:-L5-aG_-ioSFT1S5i3aa:bnfp4nl)*

**Comment by RoyalSix** [comment]
Reviewed 5 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/88)*

**Comment by RoyalSix** [comment]
Code review: LGTM

**Pull request merged**
