### PR TITLE
Refactor of Reducers

### PR DESCRIPTION
**Pull request by RoyalSix**
issue unfoldingWord-dev/translationCore#1989

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/56)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56)*

**Comment by mannycolon** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[Container.js, line 35 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk8xh2eGiWZSqjQOjU:-Knk8xh2eGiWZSqjQOjV:bs0jw1j) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L35)):*
> ```JavaScript
>             paneSettings.splice(key, 1);
>             actions.setToolSettings(NAMESPACE, 'currentPaneSettings', paneSettings);
>         }
> ```

maybe add an else if settingsReducer.toolsSettings.ScripturePane is undefined and log  message saying that for future debugging 

---

*[Container.js, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk9BXtYPsnOZosGuxJ:-Knk9BXtYPsnOZosGuxK:bn58acx) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L48)):*
> ```JavaScript
>     selectSourceLanguage(event) {
>         // let { settingsReducer } = this.props;
>         // let staticPaneSettings = settingsReducer.toolsSettings[NAMESPACE].staticPaneSettings;
> ```

I forgot to delete this commented out code. do you mind removing it?

---

*[Container.js, line 67 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk9LOUK-lop2hyv3CO:-Knk9LOUK-lop2hyv3CP:bmffc0b) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L67)):*
> ```JavaScript
>                 actions.setToolSettings(NAMESPACE, 'currentPaneSettings', currentPaneSettings);
>                 this.setState({ modalVisibility: false });
>             }
> ```

same here maybe add an else as well to help future debugging 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Container.js, line 48 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk9BXtYPsnOZosGuxJ:-KnkA9uYghUGaTOU8bKu:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L48)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I forgot to delete this commented out code. do you mind removing it?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Container.js, line 35 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk8xh2eGiWZSqjQOjU:-KnkAC7zwdwk5QldeJB8:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L35)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe add an else if settingsReducer.toolsSettings.ScripturePane is undefined and log  message saying that for future debugging 
</blockquote></details>

Done.

---

*[Container.js, line 67 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56#-Knk9LOUK-lop2hyv3CO:-KnkABU-lQZDOoB-lQ9V:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/0489a985e4c8cd06cfc6c718ab1b59bbdf7471f7/Container.js#L67)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here maybe add an else as well to help future debugging 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56)*

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/56)*

**Pull request merged**
