### PR TITLE
Feature bspidel 3210t

### PR DESCRIPTION
**Pull request by bspidel**
#### This pull request addresses:

testing for 3210

#### How to test this pull request:

- The unit test is in:
tC_apps/ScripturePane/__tests__/Pane.test.js
It uses a snapshot
- To test in app
  - Start translationCore
  - Select a project with a long language name
  - Select Translation Words tool
  - Resize the app by dragging app edge and hiding right panel. noticing the language name

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/78)

### CODE REVIEW

**Comment by PhotoNomad0** [comment]
I see some tests.  I see a console.log, but I don't see any code changes to fix the issue.  Where is the fix?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/View.js, line 32 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/78#-L1rAMrw3il4sbUVzx8o:-L1rAMrw3il4sbUVzx8p:b-8eumuf) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/14026e1f32c3fffd8b09b89ef4084b64e6bc16c0/src/components/View.js#L32)):*
> ```JavaScript
>                     "-index "                  + index + " " +
>                     "-bibleid "                + bibleId + " " + 
>                     "-currentpanesettings "    + JSON.stringify(currentPaneSettings));
> ```

Need to remove this console log.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/78#-:-L1rB9Puj-M0VZrrk364:bcm624d)*

**Comment by PhotoNomad0** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/78)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/78#-:-L1rPcjAn1PbqvlKjb8v:bnfp4nl)*

**Comment by PhotoNomad0** [comment]
Code changes already merged in.  Language name truncation works for me.

**Comment by klappy** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/78)*

**Pull request merged**
