### PR TITLE
Adds a verse editor component

### PR DESCRIPTION
**Pull request by neutrinog**
#### Describe what your pull request addresses (Please include relevant issue numbers):
Related to https://github.com/unfoldingWord-dev/translationCore/issues/2004
- Adds a new verse editor to the scripture pane.

> NOTE: I was unable to write many tests due to issues with the current version of `material-ui`.

#### Please include detailed Test instructions for your pull request:
- Expand the scripture pane and try editing a verse!

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/108)

### CODE REVIEW

**Comment by mannycolon** [comment]
@neutrinog I thought we wanted to move the verse editor component outside the scripture pane so that it can be sued in different modules/tools like in the `wordAlignment tool` and/or the `verseCheck module`

**Comment by neutrinog** [comment]
@mannycolon sure! But Ben wanted the editor in the 0.9 release if possible so I left it where it was.
We can easily abstracted it into a new repo later.
The component itself is completely self contained so it would literally be copy and paste.

**Comment by mannycolon** [comment]
@neutrinog OK, sounds good

**Comment by mannycolon** [comment]
@neutrinog I guess address the unit test coverage and we should be good to go from there

**Comment by RoyalSix** [comment]
@neutrinog I tried editing a verse other than the current verse and my edits were made to the current verse instead

**Comment by RoyalSix** [comment]
Reviewed 26 of 31 files at r1.
Review status: 26 of 31 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/chapterView/VerseRow.js, line 46 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108#-L8Z622QrVxgdfexd5AF:-L8Z622QrVxgdfexd5AG:b-y3et6e) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/b28009b4ad689883c864fe9c882cdb22f5a882a9/src/components/chapterView/VerseRow.js#L46)):*
> ```JavaScript
>         const verseText = bibles[languageId][bibleId][chapter] ? bibles[languageId][bibleId][chapter][verseNumber] : null;
>         let direction = manifest.direction;
>         // TODO: is this line right?
> ```

@mannycolon Would you know if this line is right?

---

*[src/components/VerseEditorDialog/ReasonScreen.js, line 36 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108#-L8Z6mIrRWvsOx-0_sZK:-L8Z6mIrRWvsOx-0_sZL:b-98snql) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/b28009b4ad689883c864fe9c882cdb22f5a882a9/src/components/VerseEditorDialog/ReasonScreen.js#L36)):*
> ```JavaScript
>     super(props);
>     this._handleCheck = this._handleCheck.bind(this);
>     this.state = {
> ```

This state is not being used anywhere else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108)*

**Comment by RoyalSix** [comment]
Reviewed 5 of 31 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108)*

**Comment by RoyalSix** [comment]
https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/actions/VerseEditActions.js#L48
@neutrinog It looks like you may have to edit this method and pass down chapter/verse all the way from this action to tools container to the Scripture Pane.

This is being implicitly saved when the state changes here 
https://github.com/unfoldingWord-dev/translationCore/blob/develop/src/js/localStorage/saveMethods.js#L176

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/chapterView/VerseRow.js, line 46 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108#-L8Z622QrVxgdfexd5AF:-L8ZMvAfBI9m7k2kKeed:bz7ev18) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/b28009b4ad689883c864fe9c882cdb22f5a882a9/src/components/chapterView/VerseRow.js#L46)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

@mannycolon Would you know if this line is right?
</blockquote></details>

yes, it looks right, why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108)*

**Comment by mannycolon** [comment]
Reviewed 1 of 31 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/chapterView/VerseRow.js, line 46 at r1](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/108#-L8Z622QrVxgdfexd5AF:-L8ZOUNiAznH1Fh0cKcZ:b-cfh4sq) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/b28009b4ad689883c864fe9c882cdb22f5a882a9/src/components/chapterView/VerseRow.js#L46)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

yes, it looks right, why?
</blockquote></details>

Just was looking at the commented line, and thought you might know about it

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/108)*

**Comment by neutrinog** [comment]
Thanks I'll create a PR for that.

---

Review status: 20 of 42 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/VerseEditorDialog/ReasonScreen.js, line 36 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108#-L8Z6mIrRWvsOx-0_sZK:-L8ZaKnQGJ5aB_5EmAzE:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/b28009b4ad689883c864fe9c882cdb22f5a882a9/src/components/VerseEditorDialog/ReasonScreen.js#L36)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This state is not being used anywhere else
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/108#-:-L8ZaVb7MB24lNNFqa9N:b-lbaj7f)*

**Comment by neutrinog** [comment]
Before this can be merged in tC core needs to expose editing a specific verse.

**Comment by neutrinog** [comment]
Blocked by https://github.com/unfoldingWord-dev/translationCore/pull/4152.

**Comment by PhotoNomad0** [comment]
@neutrinog - needs to be updated with master.

**Comment by neutrinog** [comment]
This has already been updated with master. See the last commit `1655fda`.

**Comment by richmahn** [comment]
Tested with tC PR #4152

Local Tests: :lgtm: 
Code Review: :lgtm:

---

Reviewed 12 of 31 files at r1, 14 of 22 files at r2, 17 of 17 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/108#-:-L8scyd26-vhAZJpIu1x:bsl3kr9)*

**Comment by PhotoNomad0** [comment]
:lgtm: Local Tests
:lgtm: Code Review

---

Reviewed 11 of 31 files at r1, 14 of 22 files at r2, 17 of 17 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/scripturepane/108#-:-L8sh2dK6kiT6OQug0Vg:b-gr1esa)*

**Pull request merged**
