### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
run ```npm test```
Use component in main app and ensure usual functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/83)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[package.json, line 38 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zSxycDVYGFb9c-5O2:-L2zSxycDVYGFb9c-5O3:b1xpyrs) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/3b5a19c5301acda2f7201229f4722b13cb1ee6b5/package.json#L38)):*
> ```JSON
>     "jest": "^21.1.0",
>     "material-ui": "^0.17.4",
>     "react": "^15.6.2",
> ```

we dont need react?

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zSzpxt2ai3W3twP-O:-L2zSzpxt2ai3W3twP-P:b-5xtapa) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/package.json#L40)):*
> ```JSON
>     "eslint": "4.15.0",
>     "eslint-plugin-react": "7.5.1",
>     "fs-extra": "3.0.1",
> ```

bring back the latest version of fs-extra?

---

*[__tests__/ChapterViewModal.test.js, line 28 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zT54bTPzs_XwXiZ5c:-L2zT54bTPzs_XwXiZ5d:blfe8qb) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/__tests__/ChapterViewModal.test.js#L28)):*
> ```JavaScript
> 
> function validateModalTitle(enzymeWrapper, expectedTitle) {
>   let titleHeader = enzymeWrapper.find(Modal.Title);
> ```

why dont we just leave this as a constant?

---

*[__tests__/View.test.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zTR0ieSlBEKISMvEo:-L2zTR0jrU3mO14-SgCr:bcwk8k9) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/__tests__/View.test.js#L19)):*
> ```JavaScript
>   it('before Project Loaded', () => {
>     let projectState = fs.readJSONSync(project);
>     let View = (
> ```

should this be a constant?

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zT_SOtkSoFXz-rIeV:-L2zT_SOtkSoFXz-rIeW:braszyh) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/testSetUp/shim.js#L1)):*
> ```JavaScript
> global.requestAnimationFrame = (callback) => {
> ```

Do we need shim.js?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zT_SOtkSoFXz-rIeV:-L3-p8_7HD4jH8fKcSFy:bb77ufg) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/testSetUp/shim.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we need shim.js?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83)*

**Comment by RoyalSix** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[package.json, line 38 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zSxycDVYGFb9c-5O2:-L34bcnN8pShSDA-YnE_:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/3b5a19c5301acda2f7201229f4722b13cb1ee6b5/package.json#L38)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont need react?
</blockquote></details>

Done.

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zSzpxt2ai3W3twP-O:-L34baI9ozO7bmEhCDLz:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/package.json#L40)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

bring back the latest version of fs-extra?
</blockquote></details>

Done.

---

*[__tests__/ChapterViewModal.test.js, line 28 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zT54bTPzs_XwXiZ5c:-L34bb_uBZY6LFy701OC:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/__tests__/ChapterViewModal.test.js#L28)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why dont we just leave this as a constant?
</blockquote></details>

Done.

---

*[__tests__/View.test.js, line 19 at r1](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-L2zTR0ieSlBEKISMvEo:-L34bcEGA-3HdeDEeSJl:b-896fix) ([raw file](https://github.com/translationcoreapps/scripturepane/blob/024c2c3bef18e2f7ef9e94c9de5a6fbcf0fbb261/__tests__/View.test.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

should this be a constant?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83#-:-L39ZgO_cCjkIcQmhZqd:bnfp4nl)*

**Comment by mannycolon** [comment]
Reviewed 1 of 13 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/83)*

**Pull request merged**
