### PR TITLE
Feature - #2470 - Gray out (disable) sources that have already been loaded in Scripture Pane

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Addresses issue https://github.com/unfoldingWord-dev/translationCore/issues/2470

#### How to test this pull request:

Go to WA or tW. If you already have 3 sources selected, remove one. Then add a source to the Scripture pane. Any sources you still have selected should be grayed out and unselectable in the source select drop down. Test by removing all your sources, etc.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/scripturepane/75)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/75)*

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/75#-:-Kz0RG8PPm3x-T-oVIPx:bnfp4nl)*

**Comment by RoyalSix** [comment]
@richmahn All good, just resolve merge conflicts.

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/scripturepane/75)*

**Comment by richmahn** [comment]
@RoyalSix Conflicts resolved for this one.

**Comment by mannycolon** [comment]
tests are failing now
@richmahn

**Pull request merged**
